### ISSUE TITLE
Lab 1: Startup.js not found

### ISSUE THREAD

**Issue by KapilChourasia** [shivkoirala/LearnAngular#1]
Hi Shiv Sir,

I was doing Lab1 and facing below issue when run startup.html page.
"GET /Binder/Startup.js" Error (404): "Not found"
Error Image(https://user-images.githubusercontent.com/1217315/28922733-04b83f02-7864-11e7-8be8-382d24397303.png)

Directory Structure: (https://user-images.githubusercontent.com/1217315/28922807-4525ecce-7864-11e7-86a8-7274a6fb7686.png)

Can you please help me to solve this issue?

**Comment by shivkoirala** [comment]
In systemjs.config.js change this path to your path. At this moment its searching in the startup folder and as per your folder structure https://user-images.githubusercontent.com/1217315/28922807-4525ecce-7864-11e7-86a8-7274a6fb7686.png you need to put the UI path.
app: {
                main: '../Startup/Startup.js', <--- this has binder so its searching in binder.
                defaultExtension: 'js'
            }

Second as a good practice putting startup.js outside or in a separate folder like app or startup folder. UI does not seem to be a good place for it.
